stereolabs/zed-ros-wrapper

CMakeLists.txt
cfg/Zed.cfg
launch/zed_depth.launch
launch/zed_stereo.launch
launch/zed_tf.launch
package.xml
records/record_depth.sh
records/record_stereo.sh
src/zed_wrapper_node.cpp

Also add static transform and detect camera disconnection.

Add dynamic confidence

---

src/zed_wrapper_node.cpp

Now a thread won't be created each time the last one has finished. The same thread is use for all the clouds.

Point cloud processing on the same thread and minor modifications

---

src/zed_wrapper_node.cpp

This way, it's possible for the application to read fractional meters
This is compatible with REP 118
An alternative would be to publish millimetres in uint16 format
Publishing meters as a uint16 is not suitable, because it decreases the depth resolution hugely

Publish depth image as float instead of uint16_t

---

README.md

Might be confusing for beginners to see the placeholder "camera" instead of the actual zed (plus respective ID when using ´zed_multi_cam.launch´ for instance). This commit attempts to make the ReadMe file more consistent with the actual implementation.

Fix issue #106: Rename ´camera´ to ´zed´ in Readme

---

CMakeLists.txt

ros kinetic, zed_wrapper_node, compiling error on Jetson TX1.
Message error is "cannot find -lopencv_dep_cudart".
Correction on CMkaefile.txt

kinetic on Jetson TX1, zed_wrapper_node compiling error: cannot find -lopencv_dep_cudart

---

CMakeLists.txt

The cmake variable is incorrect for the opencv component.
https://github.com/opencv/opencv/blob/master/cmake/templates/OpenCVConfig.cmake.in

compile error OpenCV core not found

---

cfg/Zed.cfg
launch/zed_camera.launch
src/zed_wrapper_nodelet.cpp

This commit adds dynamic reconfigure for gain and exposure parameters and also adds them to launch files.

Add dynamic reconfigure for gain and exposure

---

src/zed_wrapper_nodelet.cpp

Publish odometry data when point cloud is subscribed. This allows to only subscribe point cloud and still have it in a transformed frame.
To test you can run `roslaunch zed_wrapper zed.launch` and add cloud topic in `rviz` with `map` as `fixed frame`.

Publish odom when point cloud is subscribed

---

urdf/zedm.urdf

`zedm.urdf` was using `ZED.stl` model, instead of `ZEDM.stl`.

Fix zedm model in zedm.urdf

---

zed_wrapper/launch/zed_camera.launch

The argument `imu_frame` was not being passed to the zed_wrapper_node.

Add imu_frame parameter to zed node

---

zed_navigation_tutorial/launch/includes/move_base.launch.xml
zed_navigation_tutorial/param/move_base_params.yaml
zed_navigation_tutorial/param/trajectory_planner_params.yaml
zed_navigation_tutorial/rviz/navigation.rviz

I modified move_base and rviz parameters in order to use TrajectoryPlannerROS instead of DWAPlannerROS in the navigation tutorial.

Replace DWA Planner with Trajectory Planner

---

zed_display_rviz/rviz/zedm.rviz
zed_wrapper/src/nodelet/src/zed_wrapper_nodelet.cpp

Fixes a downward compatibility issue reported in #298 #296

Fix downward compatibility issue  

---

zed_wrapper/src/nodelet/src/zed_wrapper_nodelet.cpp

IMU angular velocities were published in degree/sec instead of rad/sec as stated in [REP145](http://www.ros.org/reps/rep-0145.html)

Fix bug #300

---

zed_wrapper/src/nodelet/src/zed_wrapper_nodelet.cpp

For SDK major than v2.5 a direct memcpy can be used to copy SL pointcloud to ROS pointcloud2

Improved pointcloud data copy for SDK major than v2.5

---

zed_wrapper/src/nodelet/src/zed_wrapper_nodelet.cpp

Possible fix for #305. The covariances now looks reasonable.

Fixed assignment of covariances in the IMU message

---

examples/zed_rtabmap_example/README.md
examples/zed_rtabmap_example/launch/zed_rtabmap.launch

Fixed TF problems with RTABmap example

---

zed_display_rviz/rviz/zedm.rviz
zed_wrapper/launch/zed_camera.launch
zed_wrapper/src/nodelet/include/zed_wrapper_nodelet.hpp
zed_wrapper/src/nodelet/src/zed_wrapper_nodelet.cpp
zed_wrapper/urdf/zed.urdf

Fixes an issue calculating the TF tree and the Visual Odometry component

Fix TF and odometry calculation

---

zed_wrapper/CMakeLists.txt

During the command "catkin_make install", the folder "param" is not found. Indeed, the folder's name is now "params".

Fix catkin_make install : directory file "params"

---

zed_wrapper/src/nodelet/src/zed_wrapper_nodelet.cpp

Nit-pick : fix the NODELET_INFO message printed when changing dynamic reconfigure contrast setting.
Not a big deal, but since I ran across it figured I'd mention it, and providing a PR seemed the quickest way to report it.

Fix diagnostic message for contrast dyn reconfigure

---

zed_wrapper/src/nodelet/src/zed_wrapper_nodelet.cpp

Mirror the behavior of mTriggerAutoExposure
This should force the code to make a call to `setCameraSettings(sl::VIDEO_SETTINGS::WHITEBALANCE_AUTO, 1);` if mCamAutoWB is set via params at startup.

Set mTriggerAutoWB on startup if mCamAutoWB is set - 

---

zed_nodelets/src/zed_nodelet/src/zed_wrapper_nodelet.cpp

Currently `publish_imu_tf` parameter only works if the `publish_tf` parameter is set to true. For this reason, there is no way to publish static IMU TF without also publishing the `odom` TF.  This PR changes this behavior by making these two options independent.

Allow publishing IMU TF without Odom TF

---

zed_nodelets/src/zed_nodelet/src/zed_wrapper_nodelet.cpp

This pull request zeroes the cross covariance terms between R_z & Z, R_z & R_x, and R_z & R_y when the camera is in 2D mode.
The matrix indexes for the 6x6 covariance matrix from the [ROS PoseWithCovariance](https://docs.ros.org/en/noetic/api/geometry_msgs/html/msg/PoseWithCovariance.html) message for reference:
|     | x  | y  | z  | R_x | R_y | R_z |
|-----|----|----|----|-----|-----|-----|
| x   | 0  | 1  | 2  | 3   | 4   | 5   |
| y   | 6  | 7  | 8  | 9   | 10  | 11  |
| z   | 12 | 13 | 14 | 15  | 16  | 17  |
| R_x | 18 | 19 | 20 | 21  | 22  | 23  |
| R_y | 24 | 25 | 26 | 27  | 28  | 29  |
| R_z | 30 | 31 | 32 | 33  | 34  | 35  |
Currently only some of the cross-correlation terms are zeroed. A dash represents that the value is left unchanged.
|     | x | y | z    | R_x  | R_y  | R_z | …

zero Rz cross covariance terms

---

zed_nodelets/src/zed_nodelet/src/zed_wrapper_nodelet.cpp

I was wondering why planes weren't being generated except when the marker was visible. Turns out the counter only uses the marker topic and not the plane response topic. This PR fixes that.

Fix plane publish counter typo
