stereolabs/zed-ros-wrapper

launch/zed_tf.launch

Which doesn't need a rate argument

Use the newer version of tf

---

src/zed_wrapper_node.cpp

Fixes transform published for zed_tracked_frame
See related issue:
#44

Updated the nodes transforms to fick zed_tracked_frame orientation

---

CMakeLists.txt
README.md
package.xml
src/zed_wrapper_node.cpp

To free the compilation from some openCV conflicts caused by cv-bridge

Removed cv-bridge dependency

---

src/zed_wrapper_node.cpp

Removed the RGB to BGR conversion in the point cloud copy loop.

Update(PointCloud): speed up to point cloud generation thanks to the ZED SDK 1.1.0 (Access to the XYZBGRA cloud)

---

CMakeLists.txt
package.xml

Update package with **format 2** and fix reference **opencv** to **opencv3**.
Detailed information are in http://wiki.ros.org/catkin/package.xml

Update dependencies in package.xml

---

zed_wrapper/src/nodelet/src/zed_wrapper_nodelet.cpp

Point cloud is now "organized"

Fixes issue https://github.com/stereolabs/zed-ros-wrapper/issues/251

---

zed_display_rviz/rviz/zedm.rviz
zed_wrapper/src/nodelet/src/zed_wrapper_nodelet.cpp

A parenthesis was in the wrong place

Fixed pointcloud mutex

---

zed_wrapper/src/nodelet/src/zed_wrapper_nodelet.cpp

Fixes #295 and #296

---

zed_wrapper/src/nodelet/src/zed_wrapper_nodelet.cpp

Fixed units for IMU covariance matrices for angular measures

---

zed_wrapper/src/nodelet/src/zed_wrapper_nodelet.cpp

Fixed inverted odometry base changing
Fixed inverted pose TF in camera_center frame

Fixed inverted odometry base changing

---

zed_wrapper/src/nodelet/src/zed_wrapper_nodelet.cpp

Fix disparity #353

---

zed_wrapper/src/nodelet/src/zed_wrapper_nodelet.cpp

Fix a bug where Tracking was enabled subscribing to Depth image even if it was not required (no odom and no pose subscribed, depth stabilization disabled)

Fix tracking enable

---

zed_wrapper/CMakeLists.txt
zed_wrapper/src/nodelet/src/zed_wrapper_nodelet.cpp

Start frame grabbing to record SVO even if there are no subscribers

Fix issue #371

---

.gitlab-ci.yml
zed_wrapper/CMakeLists.txt
zed_wrapper/launch/zed.launch
zed_wrapper/launch/zed_camera.launch
zed_wrapper/launch/zed_camera_nodelet.launch
zed_wrapper/src/nodelet/include/zed_wrapper_nodelet.hpp
zed_wrapper/src/nodelet/src/zed_wrapper_nodelet.cpp

Added 2D mode (fixed Z and null roll/pitch)

Feat 2d mode

---

zed_wrapper/src/nodelet/src/zed_wrapper_nodelet.cpp

Fix compatibility error with SDK v2.4

Fixed bug #377

---

zed_wrapper/launch/zed_camera_nodelet.launch

Add the missing rosparam "imu_frame" in nodelet launch file

---

zed_wrapper/param/common.yaml
zed_wrapper/src/nodelet/include/zed_wrapper_nodelet.hpp
zed_wrapper/src/nodelet/src/zed_wrapper_nodelet.cpp

* Fixed SVO mode compatibility code

Added SVO compression mode parameter

---

zed_wrapper/param/common.yaml
zed_wrapper/src/nodelet/include/zed_wrapper_nodelet.hpp
zed_wrapper/src/nodelet/src/zed_wrapper_nodelet.cpp
zed_wrapper/src/tools/include/sl_tools.h
zed_wrapper/src/tools/src/sl_tools.cpp

https://github.com/stereolabs/zed-ros-wrapper/issues/388

Added stereo side-by-side publisher

---

zed_wrapper/launch/zed.launch
zed_wrapper/launch/zed_camera.launch
zed_wrapper/launch/zed_no_tf.launch
zed_wrapper/launch/zedm.launch
zed_wrapper/params/common.yaml
zed_wrapper/params/zedm.yaml
zed_wrapper/src/nodelet/include/zed_wrapper_nodelet.hpp
zed_wrapper/src/nodelet/src/zed_wrapper_nodelet.cpp

Added new parameters:
`imu_fusion` to enable/disable IMU fusion in Visual Odometry (Only ZED-M)
`self_calib` to enable/disable the initial self calibration

Feat new params

---

zed_nodelets/src/zed_nodelet/src/zed_wrapper_nodelet.cpp
zed_wrapper/params/common.yaml

Fix https://github.com/stereolabs/zed-ros-wrapper/issues/591

Fix OpenNi mode for depth

---

zed_nodelets/src/zed_nodelet/include/zed_wrapper_nodelet.hpp
zed_nodelets/src/zed_nodelet/src/zed_wrapper_nodelet.cpp
zed_wrapper/params/common.yaml

Add OD frequency to diagnostic info
Improve diagnostic info

Object detection is now asynchronous

---

latest_changes.md
zed_nodelets/CMakeLists.txt
zed_nodelets/src/tools/include/sl_tools.h
zed_nodelets/src/tools/src/sl_tools.cpp
zed_nodelets/src/zed_nodelet/include/zed_wrapper_nodelet.hpp
zed_nodelets/src/zed_nodelet/src/zed_wrapper_nodelet.cpp
zed_wrapper/params/common.yaml

* Add a service to trigger the command sl::Camera::saveAreaMap
* Add a parameter to save a valid area memory when the node closes
* Add a new sl_tools function resolveFilePath to create absolute paths from relative paths

Fix save area map

---

zed_wrapper/params/zed2.yaml
zed_wrapper/params/zed2i.yaml
zed_wrapper/params/zedm.yaml
zed_wrapper/urdf/zed_macro.urdf.xacro

fix baro and mag frame links for ZED2i

---

zed_nodelets/src/zed_nodelet/src/zed_wrapper_nodelet.cpp

Fixes the Camera ID printout on node boot

Fix general/zed_id printout
